### ISSUE TITLE
is a solution with 1820A wifi card?

### ISSUE THREAD

**Issue by pro4jhu** [Juan-VC/macOS-Mojave-on-Dell-G7-7588#1]
thank you man, i use you configuration works well ! another problem,  i have a dell 1820A wifi card, can it drive?

**Comment by Juan-VC-gh** [comment]
I do not own a DW1820A but you can try, it won’t hurt your pc. In case it does not work you can check this link (https://osxlatitude.com/forums/topic/11322-broadcom-bcm4350-cards-under-high-sierramojave/ ) and find out if you can get a working one. If it works and it’s part number is supposed to give problems let me know so I can try one of those!
